name: .NET

on:
  push:
    branches: [ vulkan-rel ]
  pull_request:
    branches: [ vulkan-rel ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Building app
      run: dotnet build -c Release -o build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build
